task: xarm_reach
viewgen_type: novel_view  # novel_view, moving_view, shaking_view, novel_fov
seed: 0
ssl_task: dynamics  # dynamics_encoder_only, dynamics, idm, no
lr_encoder: 1e-6  # 1e-7 for dmc, 1e-6 for xarm
lr_transforms_stn: 
  - 1e-5
  - 1e-5

# wandb
wandb_entity:  
wandb_key: 
wandb_project: 

checkpoints_path: 
exp_disc: ${task}/${viewgen_type}/lr_transforms_stn=${lr_transforms_stn},lr_e=${lr_encoder}/${ssl_task}
eval_dir: logs/eval/${exp_disc}/${seed}
num_episodes: 20
buffer_size: 256
batch_size_eval: 32
multi_update_schedule: linear(1, 32, 200)

# environment
modality: 'pixels'
action_repeat: ???
discount: 0.99
episode_length: 1000/${action_repeat}
train_steps: 500000/${action_repeat}

# planning
iterations: 6
num_samples: 512
num_elites: 64
mixture_coef: 0.05
min_std: 0.05
temperature: 0.5
momentum: 0.1

# learning
batch_size: 512
max_buffer_size: 1000000
horizon: 5
reward_coef: 0.5
value_coef: 0.1
consistency_coef: 2
rho: 0.5
kappa: 0.1
lr: 1e-3
std_schedule: linear(0.5, ${min_std}, 25000)
horizon_schedule: linear(1, ${horizon}, 10000) 
per_alpha: 0.6
per_beta: 0.4
grad_clip_norm: 10
seed_steps: 5000
update_freq: 2
tau: 0.01

# architecture
enc_dim: 256
mlp_dim: 512
latent_dim: 50

# misc
exp_name: default
eval_freq: 20000
eval_episodes: 10
save_video: true
save_model: true
